services:
  python-app:
    build: .
    container_name: meu-python-app
    environment:
      - MINHA_VARIAVEL_DE_AMBIENTE=valor  # Substitua pelas variáveis de ambiente necessárias
    volumes: 
      - .:/app  # Monta o diretório atual no contêiner (opcional)
    command: python main.py  # Substitua pelo nome do seu arquivo Python